version: 0.0
os: linux
files:
    - source: .
      destination: /home/ubuntu/topic-app
      overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu/topic-app
      owner: root
      group: root
      mode: 755

hooks:
    AfterInstall:
        - location: scripts/after-deploy.sh
          runas: root
