version: 0.0
os: linux
files:
    - source: .
      destination: /home/ubuntu/topic-app
      overwrite: yes

permissions:
    - object: /home/ubuntu/topic-app
      owner: ubuntu
      group: ubuntu
      mode: 755

hooks:
    AfterInstall:
        - location: scripts/after-deploy.sh
          timeout: 300
          runas: ubuntu
