version: '1'
services:
    nodeapp:
        container_name: 'nodeapp'
        build: .
        ports:
            - '8001:8001'
        depends_on:
            - topic-redis
        networks:
            - topic-redis-network
    topic-redis:
        container_name: 'noderedis'
        image: redis:alpine
        # volumes:
        # - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server --port 6379
        # extra_hosts:
        #     - 'host.docker.internal'
        ports:
            - 6379:6379
        networks:
            - topic-redis-network
networks:
    topic-redis-network:
        driver: bridge
