version: '1'
services:
    nodeapp:
        build: .
        ports:
            - '8001:8001'
        depends_on:
            - topic-redis
    topic-redis:
        image: redis:alpine
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server --requirepass $${REDIS_PASSWORD}
        ports:
            - 6379:6379
