version: '1'
services:
    nodeapp:
        build: .
        ports:
            - '8001:8001'
        depends_on:
            - topic-redis
    topic-redis:
        image: redis:alpine
        command: redis-server --requirepass ${{REDIS_PASSWORD}}
        bind:
            - 0.0.0.0:6379
