version: '1'
services:
    nodeapp:
        build: .
        ports:
            - '8001:8001'
        depends_on:
            - topic-redis
        networks:
            - topic-redis-network
    topic-redis:
        image: redis:alpine
        # volumes:
        # - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server
        ports:
            - 6379:6379
        networks:
            - topic-redis-network
networks:
    topic-redis-network:
        driver: bridge
